# Generated by Django 2.1.1 on 2019-08-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
